variable "region" { type = string  default = "us-east-1" }
variable "cluster_name" { type = string default = "swimlane-eks" }
variable "vpc_cidr" { type = string default = "10.0.0.0/16" }
variable "azs" { type = list(string) default = ["us-east-1a","us-east-1b"] }
variable "public_subnets" { type = list(string) default = ["10.0.0.0/24","10.0.1.0/24"] }
variable "private_subnets" { type = list(string) default = ["10.0.10.0/24","10.0.11.0/24"] }
variable "instance_types" { type = list(string) default = ["t3.medium"] }
variable "desired_size" { type = number default = 2 }
variable "min_size" { type = number default = 2 }
variable "max_size" { type = number default = 4 }
