apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-practical.fullname" . }}-secret
  labels:
    {{- include "devops-practical.labels" . | nindent 4 }}
stringData:
  MONGODB_URL: >-
    {{- if .Values.mongodb.auth.enabled -}}
    mongodb://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@{{ include "devops-practical.fullname" . }}-mongo:{{ .Values.mongodb.port }}/{{ .Values.mongodb.auth.database }}?authSource=admin
    {{- else -}}
    mongodb://{{ include "devops-practical.fullname" . }}-mongo:{{ .Values.mongodb.port }}/appdb
    {{- end -}}
