apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "devops-practical.fullname" . }}-mongo-pvc
  labels:
    {{- include "devops-practical.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.mongodb.storage.size }}
  storageClassName: {{ .Values.mongodb.storage.storageClass | default "" | quote }}
