apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-practical.fullname" . }}-mongo
  labels:
    {{- include "devops-practical.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "devops-practical.name" . }}
    app.kubernetes.io/component: mongo
  ports:
    - name: mongo
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
